{
  imports = [
    ./containers/mssql-2017
    ./containers/mssql-2019
    ./hardware/audio
    ./hardware/bluetooth
    ./hardware/screen
    ./services/xserver
    ./setups/fonts
    ./setups/gaming
    ./setups/printing3d
    ./setups/work
    ./themes/horizon-dark
    ./themes/horizon-light
    ./user/programs/alacritty
    ./user/programs/shell
    ./user/programs/spotify
    ./user/programs/virtualbox
    ./user/programs/vscode
    ./user/services/kdeconnect
    ./user/services/mailhog
    ./user/xsession/screen-locker
  ];
}
